Add Python version checks.
Before:

    $ python2.5 -c 'import forknanny'
    forknanny.py:35: Warning: 'with' will become a reserved keyword in Python 2.6
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "forknanny.py", line 35
        with open('/proc/self/status', 'rb') as fp:
                ^
    SyntaxError: invalid syntax

After:

    $ python2.5 -c 'import forknanny'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "forknanny.py", line 15
        b''  # Python >= 2.6 is required
          ^
    SyntaxError: invalid syntax